import * as THREE from 'three';
import { KTX2Loader } from 'three/addons/loaders/KTX2Loader.js';

const LAYERS=['wet_mud','wet_sand','sand','cracked_mud','gravel'];
export class TerrainMaterial {
  constructor({renderer,mask,assetRoot='textures/terrain',preferKTX2=false,anisotropy=4}={}){this.renderer=renderer;this.mask=mask;this.assetRoot=assetRoot;this.preferKTX2=preferKTX2;this.anisotropy=Math.min(anisotropy,renderer?.capabilities?.getMaxAnisotropy?.()||4);this.textures={};this.material=null;this.debugMode=0;}
  async init(){
    const loader=new THREE.TextureLoader(),ktx=new KTX2Loader();ktx.setTranscoderPath('vendor/basis/');ktx.detectSupport(this.renderer);ktx.setWorkerLimit(1);
    const load=async(layer,kind,srgb=false)=>{let tex=null;if(this.preferKTX2){try{tex=await ktx.loadAsync(`${this.assetRoot}/${layer}/${kind}.ktx2`);}catch{}}if(!tex)tex=await loader.loadAsync(`${this.assetRoot}/${layer}/${kind}.${kind==='nrmao'?'png':'jpg'}`);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.anisotropy=this.anisotropy;if(srgb){if('colorSpace'in tex)tex.colorSpace=THREE.SRGBColorSpace;else tex.encoding=THREE.sRGBEncoding;}return tex;};
    const loaded=await Promise.all(LAYERS.map(async layer=>[layer,{color:await load(layer,'color',true),nrmao:await load(layer,'nrmao',false)}]));for(const [layer,set] of loaded)this.textures[layer]=set;
    this.macroNoise=this.makeMacroNoise();this.material=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.9,metalness:0,side:THREE.FrontSide});this.material.name='NileTerrainSplatV740';this.installShader();this.material.customProgramCacheKey=()=>`nile-terrain-v740-${this.debugMode}`;return this.material;
  }
  makeMacroNoise(){const size=128,data=new Uint8Array(size*size*4);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const i=(y*size+x)*4,n=128+Math.round((Math.sin(x*.21)+Math.sin(y*.13)+Math.sin((x+y)*.051))*15);data[i]=data[i+1]=data[i+2]=n;data[i+3]=255;}const t=new THREE.DataTexture(data,size,size,THREE.RGBAFormat);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.needsUpdate=true;return t;}
  setDebugMode(mode=0){this.debugMode=mode;if(this.material?.userData?.shader)this.material.userData.shader.uniforms.uDebugMode.value=mode;}
  installShader(){
    const t=this.textures,m=this.material;
    m.onBeforeCompile=(shader)=>{
      const u=shader.uniforms;u.uWaterLevel={value:this.mask.waterLevel};u.uRiverHalf={value:this.mask.riverHalfWidth};u.uWetWidth={value:this.mask.wetBandWidth};u.uDebugMode={value:this.debugMode};u.uMacroNoise={value:this.macroNoise};LAYERS.forEach((layer,i)=>{u[`uColor${i}`]={value:t[layer].color};u[`uNRMAO${i}`]={value:t[layer].nrmao};});m.userData.shader=shader;
      shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 vTerrainWorld;varying vec3 vTerrainWorldNormal;').replace('#include <begin_vertex>','#include <begin_vertex>\nvTerrainWorld=(modelMatrix*vec4(transformed,1.0)).xyz;vTerrainWorldNormal=normalize(mat3(modelMatrix)*objectNormal);');
      shader.fragmentShader=shader.fragmentShader.replace('#include <common>',`#include <common>\nvarying vec3 vTerrainWorld;varying vec3 vTerrainWorldNormal;uniform float uWaterLevel,uRiverHalf,uWetWidth,uDebugMode;uniform sampler2D uMacroNoise;uniform sampler2D uColor0,uColor1,uColor2,uColor3,uColor4;uniform sampler2D uNRMAO0,uNRMAO1,uNRMAO2,uNRMAO3,uNRMAO4;float h21(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);}float vnoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(h21(i),h21(i+vec2(1,0)),f.x),mix(h21(i+vec2(0,1)),h21(i+vec2(1)),f.x),f.y);}vec2 rotuv(vec2 p,float a){float c=cos(a),s=sin(a);return mat2(c,-s,s,c)*p;}vec3 nrm(sampler2D s,vec2 uv){vec4 p=texture2D(s,uv);vec2 xy=p.rg*2.0-1.0;float z=sqrt(max(.02,1.0-dot(xy,xy)));return normalize(vec3(xy.x,z,xy.y));}float shoreDistance(vec3 wp){float center=sin(wp.z*.0105)*.34+sin(wp.z*.027+1.4)*.13;float macro=(vnoise(wp.xz*.05)-.5)*1.6;return abs(wp.x-center)-(uRiverHalf+macro*.32);}vec4 weightsAt(vec3 wp){float d=shoreDistance(wp);float n=(vnoise(wp.xz*.12)-.5)*2.0;float q=d+n*clamp(abs(d)*.18,.35,2.2);float a=1.0-smoothstep(-.42,1.18,q);float heightWet=1.0-smoothstep(uWaterLevel,uWaterLevel+1.0,wp.y);a=max(a,heightWet*.28*(1.0-smoothstep(1.0,4.5,q)));float b=smoothstep(.20,1.0,q)*(1.0-smoothstep(1.45,3.7,q));float c=smoothstep(1.55,3.2,q)*(1.0-smoothstep(7.0,11.5,q));float e=smoothstep(5.8,9.5,q)*(1.0-smoothstep(14.0,21.0,q));float f=smoothstep(12.5,20.0,q);float total=a+b+c+e+f+1e-4;return vec4(a/total,b/total,c/total,e/total);}float gravelWeight(vec4 w){return max(0.0,1.0-(w.x+w.y+w.z+w.w));}`);
      shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`float shoreD=shoreDistance(vTerrainWorld);if(shoreD<-.10)discard;vec4 tw=weightsAt(vTerrainWorld);float wg=gravelWeight(tw);float slope=1.0-clamp(vTerrainWorldNormal.y,0.0,1.0);wg+=smoothstep(.24,.68,slope)*.38;float wn=tw.x+tw.y+tw.z+tw.w+wg;tw/=wn;wg/=wn;vec2 p=vTerrainWorld.xz;vec2 uv0=rotuv(p/2.35,.2967),uv1=rotuv(p/2.75,-.12),uv2=p/3.15,uv3=rotuv(p/2.85,.541),uv4=rotuv(p/3.55,-.192);float bn=texture2D(uMacroNoise,p/58.0).r;vec2 o=vec2(5.7,-3.9);vec4 c0=mix(texture2D(uColor0,uv0),texture2D(uColor0,rotuv(uv0*1.071+o,.41)),.18+.24*bn);vec4 c1=mix(texture2D(uColor1,uv1),texture2D(uColor1,rotuv(uv1*1.053-o,.27)),.16+.20*bn);vec4 c2=mix(texture2D(uColor2,uv2),texture2D(uColor2,rotuv(uv2*1.083+o,-.33)),.16+.24*bn);vec4 c3=mix(texture2D(uColor3,uv3),texture2D(uColor3,rotuv(uv3*1.061-o,.22)),.15+.22*bn);vec4 c4=mix(texture2D(uColor4,uv4),texture2D(uColor4,rotuv(uv4*1.077+o,-.19)),.15+.20*bn);c0.rgb*=vec3(.72,.69,.64);c1.rgb*=vec3(.82,.77,.69);c2.rgb*=vec3(.90,.84,.74);c3.rgb*=vec3(.82,.74,.64);c4.rgb*=vec3(.80,.76,.69);vec3 terrainColor=c0.rgb*tw.x+c1.rgb*tw.y+c2.rgb*tw.z+c3.rgb*tw.w+c4.rgb*wg;float l=dot(terrainColor,vec3(.299,.587,.114));terrainColor=mix(vec3(l),terrainColor,.78);terrainColor*=mix(.97,1.035,bn);if(uDebugMode>0.5&&uDebugMode<1.5)terrainColor=vec3(tw.x,tw.y+tw.z*.55,tw.w);else if(uDebugMode>1.5&&uDebugMode<2.5){float sd=clamp(shoreD/20.0,0.0,1.0);terrainColor=vec3(sd);}else if(uDebugMode>2.5&&uDebugMode<3.5)terrainColor=vec3(1.0-smoothstep(0.0,uWetWidth,shoreD));else if(uDebugMode>3.5)terrainColor=vec3(vnoise(p*.055));diffuseColor.rgb*=terrainColor;`);
      shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>',`vec4 n0=texture2D(uNRMAO0,uv0),n1=texture2D(uNRMAO1,uv1),n2=texture2D(uNRMAO2,uv2),n3=texture2D(uNRMAO3,uv3),n4=texture2D(uNRMAO4,uv4);float terrainR=n0.b*tw.x+n1.b*tw.y+n2.b*tw.z+n3.b*tw.w+n4.b*wg;float wet=tw.x+tw.y*.52;roughnessFactor*=mix(clamp(terrainR,.72,1.0),clamp(terrainR*.68,.34,.70),wet);`);
      shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>',`vec3 tn=nrm(uNRMAO0,uv0)*tw.x+nrm(uNRMAO1,uv1)*tw.y+nrm(uNRMAO2,uv2)*tw.z+nrm(uNRMAO3,uv3)*tw.w+nrm(uNRMAO4,uv4)*wg;tn=normalize(tn);vec3 worldN=normalize(vec3(tn.x*.42,max(.38,tn.y),tn.z*.42));normal=normalize(mix(normal,normalize(mat3(viewMatrix)*worldN),.22));`);
      shader.fragmentShader=shader.fragmentShader.replace('#include <aomap_fragment>',`float terrainAO=n0.a*tw.x+n1.a*tw.y+n2.a*tw.z+n3.a*tw.w+n4.a*wg;reflectedLight.indirectDiffuse*=mix(.87,1.0,terrainAO);`);
    };m.needsUpdate=true;
  }
}
