class GameAudio {
  constructor(){this.ctx=null;}
  init(){if(!this.ctx){const AudioContext=window.AudioContext||window.webkitAudioContext;this.ctx=new AudioContext();}if(this.ctx.state==='suspended')this.ctx.resume();}
  playCollect(){if(!this.ctx)return;const now=this.ctx.currentTime,osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='triangle';osc.frequency.setValueAtTime(523.25,now);osc.frequency.exponentialRampToValueAtTime(1046.5,now+.18);gain.gain.setValueAtTime(.2,now);gain.gain.linearRampToValueAtTime(.01,now+.22);osc.connect(gain);gain.connect(this.ctx.destination);osc.start(now);osc.stop(now+.22);}
  playPowerup(){if(!this.ctx)return;const now=this.ctx.currentTime;[440,554.37,659.25,880].forEach((freq,i)=>{const osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,now+i*.06);gain.gain.setValueAtTime(.15,now+i*.06);gain.gain.linearRampToValueAtTime(.01,now+i*.06+.15);osc.connect(gain);gain.connect(this.ctx.destination);osc.start(now+i*.06);osc.stop(now+i*.06+.15);});}
  playSplash(){if(!this.ctx)return;const now=this.ctx.currentTime,bufSize=this.ctx.sampleRate*.12,buffer=this.ctx.createBuffer(1,bufSize,this.ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<bufSize;i++)data[i]=(Math.random()*2-1)*(1-i/bufSize);const noise=this.ctx.createBufferSource();noise.buffer=buffer;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.setValueAtTime(500,now);const gain=this.ctx.createGain();gain.gain.setValueAtTime(.12,now);gain.gain.linearRampToValueAtTime(.01,now+.12);noise.connect(filter);filter.connect(gain);gain.connect(this.ctx.destination);noise.start(now);}
  playHit(){if(!this.ctx)return;const now=this.ctx.currentTime,osc=this.ctx.createOscillator(),gain=this.ctx.createGain();osc.type='sawtooth';osc.frequency.setValueAtTime(150,now);osc.frequency.exponentialRampToValueAtTime(30,now+.4);gain.gain.setValueAtTime(.35,now);gain.gain.exponentialRampToValueAtTime(.01,now+.4);osc.connect(gain);gain.connect(this.ctx.destination);osc.start(now);osc.stop(now+.4);}
}
window.gameAudio=new GameAudio();
