from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, got {count}")
    return text.replace(old, new, 1)

root = Path('.')

app_path = root / 'android-app/app/src/main/java/com/vidalost/biblegames/App.kt'
app = app_path.read_text()
app = replace_once(app, 'import android.net.Uri\n', 'import android.net.Uri\nimport android.widget.Toast\n', 'Toast import')
app = replace_once(app, 'private const val ACCESS_POLL_MS = 3_000L\n', 'private const val ACCESS_POLL_MS = 3_000L\nprivate const val ACCESS_RETRY_MS = 900L\n', 'access retry constant')
app = replace_once(app, '    var accessError by remember(userId) { mutableStateOf<String?>(null) }\n    var accessRetry by remember(userId) { mutableStateOf(0) }\n', '', 'obsolete access UI states')
app = replace_once(app, '''    val presence = remember(userId) {\n        if (userId.matches(Regex("^[0-9]{5,20}$"))) AppPresenceClient(context, cloud, userId) else null\n    }\n''', '''    // Do not open the presence WebSocket until access is verified. Besides\n    // preventing blocked/unverified sessions from appearing online, this avoids\n    // competing with the tiny access request during cold mobile/VPN startup.\n    val presence = remember(userId, accessChecked, isBanned) {\n        if (userId.matches(Regex("^[0-9]{5,20}$")) && accessChecked && !isBanned)\n            AppPresenceClient(context, cloud, userId)\n        else null\n    }\n''', 'presence gating')
old_access = '''    LaunchedEffect(userId, accessRetry) {\n        if (userId.matches(Regex("^[0-9]{5,20}$")) && userId != ADMIN_ID) {\n            syncing = true\n            accessError = null\n            if (!isBanned) accessChecked = false\n\n            cloud.checkAccess(userId)\n                .onSuccess { banned ->\n                    applyAccessState(banned)\n                    if (!banned) {\n                        cloud.syncProfile(userId, profile).onSuccess {\n                            profile = it\n                            saveLocalProfile(context, it)\n                            if (it.lastGames.isNotEmpty()) {\n                                history = normalizeHistory(history + it.lastGames)\n                                prefs.edit().putString(HISTORY_KEY, history.joinToString(",")).apply()\n                            }\n                        }\n                    }\n                }\n                .onFailure { error ->\n                    if (!isBanned) accessChecked = false\n                    accessError = error.message ?: "Не удалось быстро проверить доступ"\n                }\n            syncing = false\n        } else {\n            accessChecked = false\n            accessError = null\n        }\n    }\n\n    // Poll independently from accessChecked. This is important for a cached\n    // banned account: unblocking in the admin panel must restore access without\n    // forcing the player to change and re-enter the Telegram ID.\n    LaunchedEffect(userId) {\n        if (!userId.matches(Regex("^[0-9]{5,20}$")) || userId == ADMIN_ID) return@LaunchedEffect\n        delay(ACCESS_POLL_MS)\n        while (true) {\n            val wasBanned = isBanned\n            cloud.checkAccess(userId).onSuccess { banned ->\n                applyAccessState(banned)\n                if (wasBanned && !banned) {\n                    syncing = true\n                    cloud.syncProfile(userId, profile).onSuccess {\n                        profile = it\n                        saveLocalProfile(context, it)\n                        if (it.lastGames.isNotEmpty()) {\n                            history = normalizeHistory(history + it.lastGames)\n                            prefs.edit().putString(HISTORY_KEY, history.joinToString(",")).apply()\n                        }\n                    }\n                    syncing = false\n                }\n            }\n            delay(ACCESS_POLL_MS)\n        }\n    }\n'''
new_access = '''    // One access monitor owns both startup verification and later ban/unban\n    // refreshes. Network failures retry automatically; there are no overlapping\n    // manual + polling requests and no raw timeout screen for the player.\n    LaunchedEffect(userId) {\n        if (!userId.matches(Regex("^[0-9]{5,20}$")) || userId == ADMIN_ID) {\n            accessChecked = false\n            return@LaunchedEffect\n        }\n        if (!isBanned) accessChecked = false\n        while (true) {\n            val firstVerification = !accessChecked\n            val wasBanned = isBanned\n            val result = cloud.checkAccess(userId)\n            result.onSuccess { banned ->\n                applyAccessState(banned)\n                if (!banned && (firstVerification || wasBanned)) {\n                    syncing = true\n                    appScope.launch {\n                        cloud.syncProfile(userId, profile).onSuccess {\n                            profile = it\n                            saveLocalProfile(context, it)\n                            if (it.lastGames.isNotEmpty()) {\n                                history = normalizeHistory(history + it.lastGames)\n                                prefs.edit().putString(HISTORY_KEY, history.joinToString(",")).apply()\n                            }\n                        }\n                        syncing = false\n                    }\n                }\n            }\n            delay(if (result.isSuccess) ACCESS_POLL_MS else ACCESS_RETRY_MS)\n        }\n    }\n'''
app = replace_once(app, old_access, new_access, 'unified access monitor')
app = replace_once(app, '''    fun openGame(game: GameKey) {\n        if (!accessChecked || isBanned) return\n''', '''    fun openGame(game: GameKey) {\n        if (!accessChecked) {\n            Toast.makeText(context, "Проверяем доступ. Игра откроется после подтверждения.", Toast.LENGTH_SHORT).show()\n            return\n        }\n        if (isBanned) return\n''', 'game access feedback')
app = replace_once(app, '''    if (userId.isNotBlank() && !accessChecked && !isBanned) {\n        AccessVerificationScreen(\n            error = accessError,\n            onRetry = { accessRetry += 1 },\n            onLogout = {\n                prefs.edit().remove(ID_KEY).apply()\n                userId = ""\n            },\n            onSupport = { supportOpen = true },\n        )\n        return\n    }\n\n''', '', 'blocking verification screen')
app = replace_once(app, '''                syncing = syncing,\n                profile = profile,\n''', '''                syncing = syncing,\n                accessReady = accessChecked,\n                profile = profile,\n''', 'HomeScreen access argument')
app = replace_once(app, '''    syncing: Boolean,\n    profile: PlayerProfile,\n''', '''    syncing: Boolean,\n    accessReady: Boolean,\n    profile: PlayerProfile,\n''', 'HomeScreen signature')
app = replace_once(app, '''                        StatusPill(if (syncing) "Синхронизация…" else "Прогресс сохранён", if (syncing) Cyan else Color(0xFF059669), if (syncing) "↻" else "✓")\n''', '''                        StatusPill(\n                            when {\n                                !accessReady -> "Проверяем доступ…"\n                                syncing -> "Синхронизация…"\n                                else -> "Прогресс сохранён"\n                            },\n                            if (!accessReady || syncing) Cyan else Color(0xFF059669),\n                            if (!accessReady || syncing) "↻" else "✓",\n                        )\n''', 'home access status pill')
app_path.write_text(app)

cloud_path = root / 'android-app/app/src/main/java/com/vidalost/biblegames/data/CloudRepository.kt'
cloud = cloud_path.read_text()
cloud = replace_once(cloud, '''    /** Access checks must never hold the first screen behind OkHttp's normal\n     * retry/timeout budget. The server action is tiny and safe to repeat on the\n     * next poll, so use a strict call deadline and no transparent retry. */\n    private val accessClient: OkHttpClient = OkHttpClient.Builder()\n        .protocols(listOf(Protocol.HTTP_2, Protocol.HTTP_1_1))\n        .connectTimeout(3, TimeUnit.SECONDS)\n        .readTimeout(3, TimeUnit.SECONDS)\n        .writeTimeout(3, TimeUnit.SECONDS)\n        .callTimeout(5, TimeUnit.SECONDS)\n        .retryOnConnectionFailure(false)\n        .build()\n''', '''    /** Access status is a tiny read-only request. HTTP/1.1 is deliberately\n     * used here because some mobile VPN/carrier paths repeatedly stall HTTP/2\n     * setup. The whole call is still bounded so a bad network cannot freeze UI. */\n    private val accessClient: OkHttpClient = OkHttpClient.Builder()\n        .protocols(listOf(Protocol.HTTP_1_1))\n        .connectTimeout(5, TimeUnit.SECONDS)\n        .readTimeout(6, TimeUnit.SECONDS)\n        .writeTimeout(6, TimeUnit.SECONDS)\n        .callTimeout(7, TimeUnit.SECONDS)\n        .retryOnConnectionFailure(true)\n        .build()\n''', 'access client transport')
cloud = replace_once(cloud, '''    suspend fun checkAccess(id: String): Result<Boolean> = withContext(Dispatchers.IO) {\n        runCatching {\n            val payload = JSONObject().put("action", "accessStatus")\n            val json = postWith(accessClient, "$CORE/android/compat", JSONObject().put("payload", payload).put("androidUserId", id))\n            json.optBoolean("isBanned", false)\n        }\n    }\n''', '''    suspend fun checkAccess(id: String): Result<Boolean> = withContext(Dispatchers.IO) {\n        runCatching {\n            val request = Request.Builder()\n                .url("$CORE/android/access?id=$id")\n                .get()\n                .header("Accept", "application/json")\n                .header("Origin", "https://vidalost.github.io")\n                .header("Cache-Control", "no-store")\n                .header("User-Agent", "BibleGames-Android/2.6 Native")\n                .build()\n            accessClient.newCall(request).execute().use { response ->\n                val payload = response.body?.string().orEmpty()\n                val json = runCatching { JSONObject(payload) }.getOrNull()\n                if (!response.isSuccessful || json == null) {\n                    throw IOException(json?.optString("error")?.takeIf { it.isNotBlank() } ?: "Не удалось проверить доступ")\n                }\n                json.optBoolean("isBanned", false)\n            }\n        }\n    }\n''', 'GET access check')
cloud_path.write_text(cloud)

core_path = root / 'cloudflare/app-core-worker/src/index-v4.js'
core = core_path.read_text()
needle = "    if (url.pathname !== '/android/compat') return core.fetch(request, env, ctx);\n"
insert = '''    if (url.pathname === '/android/access' && request.method === 'GET') {\n      try {\n        if (!isAllowedOrigin(request, env)) throw httpError(403, 'Origin not allowed');\n        const androidUserId = String(url.searchParams.get('id') || '').trim();\n        if (!/^\\d{5,20}$/.test(androidUserId)) throw httpError(400, 'Bad Android user id');\n        if (androidUserId === String(env.ADMIN_TELEGRAM_ID || '')) throw httpError(403, 'Admin login is not allowed in Android ID mode');\n        const store = env.USERS.get(env.USERS.idFromName('global'));\n        const access = await callStore(store, '/access', { id: androidUserId });\n        return json({ success: true, isBanned: Boolean(access.isBanned), source: 'cloudflare-sql-android-access-get' }, 200, cors);\n      } catch (error) {\n        return json({ success: false, error: String(error?.message || 'Server error') }, Number(error?.status || 500), cors);\n      }\n    }\n\n    if (url.pathname !== '/android/compat') return core.fetch(request, env, ctx);\n'''
core = replace_once(core, needle, insert, 'GET /android/access route')
core_path.write_text(core)

gradle_path = root / 'android-app/app/build.gradle'
gradle = gradle_path.read_text()
gradle = replace_once(gradle, 'versionCode 18', 'versionCode 19', 'versionCode')
gradle = replace_once(gradle, "versionName '2.6.6-native'", "versionName '2.6.7-native'", 'versionName')
gradle_path.write_text(gradle)

check_path = root / 'scripts/check-android-ban-enforcement.mjs'
check = check_path.read_text()
check = check.replace("need(app, 'cloud.checkAccess(userId)', 'initial fast access check missing');", "need(app, 'delay(if (result.isSuccess) ACCESS_POLL_MS else ACCESS_RETRY_MS)', 'automatic access retry loop missing');")
check = check.replace("need(app, 'AccessVerificationScreen(', 'initial access verification screen missing');", "reject(app, 'if (userId.isNotBlank() && !accessChecked && !isBanned)', 'startup still blocks on verification screen');")
check = check.replace("need(cloud, 'callTimeout(5, TimeUnit.SECONDS)', 'fast access call deadline missing');", "need(cloud, 'callTimeout(7, TimeUnit.SECONDS)', 'bounded access call deadline missing');")
check = check.replace("need(cloud, 'retryOnConnectionFailure(false)', 'access check can still retry for tens of seconds');", "need(cloud, 'protocols(listOf(Protocol.HTTP_1_1))', 'access transport is not VPN-friendly HTTP/1.1');")
check = check.replace("need(cloud, 'postWith(accessClient, \"$CORE/android/compat\"', 'accessStatus does not use the fast client');", "need(cloud, '.url(\"$CORE/android/access?id=$id\")', 'dedicated GET access endpoint missing');")
check = check.replace("need(core, \"callStore(store, '/access', { id: androidUserId })\", 'backend accessStatus still performs a profile sync');", "need(core, \"url.pathname === '/android/access'\", 'dedicated Android access route missing');\nneed(core, \"callStore(store, '/access', { id: androidUserId })\", 'backend access route does not use read-only lookup');")
check = check.replace("need(gradle, \"versionName '2.6.6-native'\", 'Android version was not bumped');", "need(gradle, \"versionName '2.6.7-native'\", 'Android version was not bumped');")
check_path.write_text(check)

print('Applied Android access resilience patch 2.6.7')
