// Ordered entry list for the eager web bundle.
// index.html loads the built bundles from web/dist/; this file is the source of truth
// for what goes into them and in which order. Load order is significant: these are
// classic scripts that share one global scope, exactly as the old <script defer> tags did.

export const styleSources = [
  'web/styles/tokens.css',
  'web/styles/startup-gamehub-loader.css',
  'web/styles/style.css',
  'web/styles/admin-enhancements.css',
  'web/styles/home-enhancements.css',
  'web/styles/home-controls.css',
  'web/styles/home-parallax-v1.css',
  'web/styles/admin-live-v3.css',
  'web/styles/broadcast-cloudflare.css',
  'web/styles/error-system.css',
  'web/styles/support-center.css',
  'web/styles/admin-compact-lists.css',
  'web/styles/admin-shell-v3.css',
  'web/styles/admin-live-compact.css',
  'web/styles/room-invite.css',
  'web/styles/room-qr-brand.css',
  'web/styles/games-mobile-polish.css',
  'web/games/kids-ark-pairs.css',
  'web/games/quartet-mobile.css',
  'web/games/quartet-v4-preview.css',
  'web/styles/quartet-v43-smooth.css',
  'web/styles/quartet-gesture-guard.css',
  'web/styles/app-motion.css',
  'web/styles/word-games-upgrade.css',
  'web/styles/bible-wow-word-flow.css',
  'web/styles/biblical-match-three-v38.css',
  // Оформление идёт последним: оно задаёт вид поверх исторических слоёв.
  'web/styles/typography.css',
  'web/styles/surfaces.css',
  'web/styles/game-shell.css',
  'web/styles/admin-usability.css',
  'web/styles/word-games-polish.css',
  'web/styles/game-titles-polish.css',
  'web/styles/sacred-word-polish.css',
  'web/styles/lobby-polish.css',
  'web/styles/leaderboard.css',
  'web/styles/game-rules.css',
  // Собирается scripts/build-dark-theme.mjs из всех перечисленных выше файлов,
  // поэтому обязана идти последней.
  'web/styles/dark-theme.css',
];

export const scriptSources = [
  'web/js/android-runtime.js',
  'web/js/backend-bridge.js',
  'web/js/referral-survey.js',
  'web/js/error-system.js',
  'web/js/startup-gamehub-loader.js',
  'web/js/startup-coordinator.js',
  'web/games/kids-ark-pairs.js',
  'web/js/quartet-production-v43-loader.js',
  'web/js/app.js',
  'web/js/home-parallax-v1.js',
  'web/js/cloudflare-request-budget.js',
  'web/games/biblical-match-three-progress.js',
  'web/js/bmt-stars-cloud-sync.js',
  'web/js/biblical-match-three-launcher.js',
  'web/js/android-download-menu.js',
  'web/js/android-performance.js',
  'web/js/bible-sketch-launcher.js',
  'web/js/room-invite.js',
  'web/js/room-qr-brand.js',
  'web/js/room-qr-scanner.js',
  'web/js/room-qr-addon.js',
  'web/js/telegram-gesture-guard.js',
  'web/js/game-shell.js',
  'web/js/quartet-chat-addon.js',
  'web/js/quartet-v43-smooth-ui.js',
  'web/js/quartet-v45-card-id-fix.js',
  'web/js/quartet-v44-overlay-fix.js',
  'web/js/quartet-v46-cleanup.js',
  'web/js/early-init.js',
  'web/js/three-gate.js',
  'web/js/system-icons.js',
  'web/js/v22-home-art.js',
  'web/js/v43-biblical-treasures-lamp-stability.js',
  'web/js/v22-game-loader.js',
  'web/js/v24-biblical-treasures-board.js',
  'web/js/v29-biblical-treasures-hotfix.js',
  'web/js/v36-biblical-treasures-special-art.js',
  'web/js/v37-biblical-treasures-lamp-swipe.js',
  'web/js/v38-biblical-treasures-experience.js',
  'web/js/admin-enhancements.js',
  'web/js/broadcast-admin-mount.js',
  'web/js/broadcast-cloudflare.js',
  'web/js/home-enhancements.js',
  'web/js/home-controls.js',
  'web/js/app-motion.js',
  'web/js/word-games-upgrade-lite.js',
  'web/js/bible-wow-word-flow.js',
  'web/js/wordsearch-classic-engine.js',
  'web/js/network-warmup.js',
  'web/js/telemetry.js',
  'web/js/presence-identity.js',
  'web/js/presence-game-bridge.js',
  'web/js/admin-live-v3.js',
  'web/js/admin-live-rescue.js',
  'web/js/admin-shell-v3.js',
  'web/js/admin-live-modal-safety.js',
  'web/js/support-center.js',
  'web/js/game-rules-demos.js',
  'web/js/game-rules.js',
  'web/js/leaderboard.js',
  'web/js/leaderboard-admin.js',
];
const bundled = new Set([...styleSources, ...scriptSources]);

/** True when a stylesheet or script ships to the browser inside the eager bundle. */
export const isBundled = (source) => bundled.has(source);
