package com.shatteredpixel.shatteredpixeldungeon.admin;

/**
 * Каталог всех предметов игры. Файл собирается скриптом build/gencatalog.py
 * по дизассемблированному коду, поэтому в списке оказывается каждый предмет,
 * который игра вообще умеет создавать.
 */
final class AdminCatalog {

	static final String[] CATEGORIES = {
		"ОРУЖИЕ", "МЕТАНИЕ", "БРОНЯ", "ЖЕЗЛЫ", "КОЛЬЦА", "АРТЕФАКТЫ", "ЗЕЛЬЯ", "СВИТКИ", "ЧАРЫ", "РУНЫ", "ТАЛИСМАНЫ", "БОМБЫ", "СЕМЕНА", "ЕДА", "КВЕСТОВЫЕ", "СУМКИ", "ПРОЧЕЕ"
	};

	private static final String[] C0 = {   // ОРУЖИЕ
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.AssassinsBlade",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.BattleAxe",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Crossbow",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Cudgel",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Dagger",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Dirk",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Flail",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Gauntlet",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Glaive",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Gloves",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Greataxe",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Greatshield",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Greatsword",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.HandAxe",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Katana",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Longsword",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Mace",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.MagesStaff",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Quarterstaff",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Rapier",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.RoundShield",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.RunicBlade",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Sai",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Scimitar",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Shortsword",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Sickle",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Spear",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Sword",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.WarHammer",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.WarScythe",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.Whip",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.melee.WornShortsword",
	};

	private static final String[] C1 = {   // МЕТАНИЕ
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Bolas",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.FishingSpear",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ForceCube",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.HeavyBoomerang",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Javelin",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Kunai",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Shuriken",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingClub",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingHammer",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingKnife",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingSpear",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingSpike",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.ThrowingStone",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Tomahawk",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.Trident",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.AdrenalineDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.BlindingDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.ChillingDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.CleansingDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.DisplacingDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.HealingDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.HolyDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.IncendiaryDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.ParalyticDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.PoisonDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.RotDart",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.missiles.darts.ShockingDart",
	};

	private static final String[] C2 = {   // БРОНЯ
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.ClericArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.ClothArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.DuelistArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.HuntressArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.LeatherArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.MageArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.MailArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.PlateArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.RogueArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.ScaleArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.armor.WarriorArmor",
	};

	private static final String[] C3 = {   // ЖЕЗЛЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfBlastWave",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfCorrosion",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfCorruption",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfDisintegration",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfFireblast",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfFrost",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfLightning",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfLivingEarth",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfMagicMissile",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfPrismaticLight",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfRegrowth",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfRegrowth$Dewcatcher$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfRegrowth$Seedpod$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfTransfusion",
		"com.shatteredpixel.shatteredpixeldungeon.items.wands.WandOfWarding",
	};

	private static final String[] C4 = {   // КОЛЬЦА
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfAccuracy",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfArcana",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfElements",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfEnergy",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfEvasion",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfForce",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfFuror",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfHaste",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfMight",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfSharpshooting",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfTenacity",
		"com.shatteredpixel.shatteredpixeldungeon.items.rings.RingOfWealth",
	};

	private static final String[] C5 = {   // АРТЕФАКТЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.AlchemistsToolkit",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.CapeOfThorns",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.ChaliceOfBlood",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.CloakOfShadows",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.DriedRose",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.DriedRose$Petal",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.EtherealChains",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.HolyTome",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.HornOfPlenty",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.LloydsBeacon",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.MasterThievesArmband",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.SandalsOfNature",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.SkeletonKey",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.TalismanOfForesight",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.TimekeepersHourglass",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.TimekeepersHourglass$sandBag",
		"com.shatteredpixel.shatteredpixeldungeon.items.artifacts.UnstableSpellbook",
	};

	private static final String[] C6 = {   // ЗЕЛЬЯ
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfExperience",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfFrost",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfHaste",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfHealing",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfInvisibility",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfLevitation",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfLiquidFlame",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfMindVision",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfParalyticGas",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfPurity",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfStrength",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfToxicGas",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.AquaBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.BlizzardBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.CausticBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.InfernalBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.ShockingBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.brews.UnstableBrew",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfAquaticRejuvenation",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfArcaneArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfDragonsBlood",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfFeatherFall",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfHoneyedHealing",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfIcyTouch",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfMight",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.elixirs.ElixirOfToxicEssence",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfCleansing",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfCorrosiveGas",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfDivineInspiration",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfDragonsBreath",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfEarthenArmor",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfMagicalSight",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfMastery",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfShielding",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfShroudingFog",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfSnapFreeze",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfStamina",
		"com.shatteredpixel.shatteredpixeldungeon.items.potions.exotic.PotionOfStormClouds",
	};

	private static final String[] C7 = {   // СВИТКИ
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfIdentify",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfLullaby",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfMagicMapping",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfMirrorImage",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRage",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRecharging",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRemoveCurse",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfRetribution",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfTeleportation",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfTerror",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfTransmutation",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfUpgrade",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfAntiMagic",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfChallenge",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfDivination",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfDread",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfEnchantment",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfForesight",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfMetamorphosis",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfMysticalEnergy",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfPassage",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfPrismaticImage",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfPsionicBlast",
		"com.shatteredpixel.shatteredpixeldungeon.items.scrolls.exotic.ScrollOfSirensSong",
	};

	private static final String[] C8 = {   // ЧАРЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.Alchemize",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.BeaconOfReturning",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.CurseInfusion",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.MagicalInfusion",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.PhaseShift",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.ReclaimTrap",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.Recycle",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.SummonElemental",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.TelekineticGrab",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.UnstableSpell",
		"com.shatteredpixel.shatteredpixeldungeon.items.spells.WildEnergy",
	};

	private static final String[] C9 = {   // РУНЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfAggression",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfAugmentation",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfBlast",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfBlink",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfClairvoyance",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfDeepSleep",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfDetectMagic",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfEnchantment",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfFear",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfFlock",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfIntuition",
		"com.shatteredpixel.shatteredpixeldungeon.items.stones.StoneOfShock",
	};

	private static final String[] C10 = {   // ТАЛИСМАНЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.ChaoticCenser",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.CrackedSpyglass",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.DimensionalSundial",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.ExoticCrystals",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.EyeOfNewt",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.FerretTuft",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.MimicTooth",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.MossyClump",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.ParchmentScrap",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.PetrifiedSeed",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.RatSkull",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.SaltCube",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.ShardOfOblivion",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.ThirteenLeafClover",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.TrapMechanism",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.TrinketCatalyst",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.TrinketCatalyst$RandomTrinket",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.VialOfBlood",
		"com.shatteredpixel.shatteredpixeldungeon.items.trinkets.WondrousResin",
	};

	private static final String[] C11 = {   // БОМБЫ
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.ArcaneBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.Bomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.Bomb$ConjuredBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.Bomb$DoubleBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.Firebomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.FlashBangBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.FrostBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.HolyBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.Noisemaker",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.RegrowthBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.ShrapnelBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.SmokeBomb",
		"com.shatteredpixel.shatteredpixeldungeon.items.bombs.WoollyBomb",
	};

	private static final String[] C12 = {   // СЕМЕНА
		"com.shatteredpixel.shatteredpixeldungeon.plants.BlandfruitBush$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Blindweed$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Earthroot$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Fadeleaf$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Firebloom$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Icecap$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Mageroyal$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Rotberry$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Sorrowmoss$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Starflower$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Stormvine$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Sungrass$Seed",
		"com.shatteredpixel.shatteredpixeldungeon.plants.Swiftthistle$Seed",
	};

	private static final String[] C13 = {   // ЕДА
		"com.shatteredpixel.shatteredpixeldungeon.items.food.Berry",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.Blandfruit",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.Blandfruit$Chunks",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.ChargrilledMeat",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.FrozenCarpaccio",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.MeatPie",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.MysteryMeat",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.Pasty",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.Pasty$FishLeftover",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.PhantomMeat",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.SmallRation",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.StewedMeat",
		"com.shatteredpixel.shatteredpixeldungeon.items.food.SupplyRation",
	};

	private static final String[] C14 = {   // КВЕСТОВЫЕ
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.AlchemyPage",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.GuidePage",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.Guidebook",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.RegionLorePage$Caves",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.RegionLorePage$City",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.RegionLorePage$Halls",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.RegionLorePage$Prison",
		"com.shatteredpixel.shatteredpixeldungeon.items.journal.RegionLorePage$Sewers",
		"com.shatteredpixel.shatteredpixeldungeon.items.keys.CrystalKey",
		"com.shatteredpixel.shatteredpixeldungeon.items.keys.GoldenKey",
		"com.shatteredpixel.shatteredpixeldungeon.items.keys.IronKey",
		"com.shatteredpixel.shatteredpixeldungeon.items.keys.WornKey",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.CeremonialCandle",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.CorpseDust",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.DarkGold",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.DwarfToken",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.Embers",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.EscapeCrystal",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.GooBlob",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.ImpStatue",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.MetalShard",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.Pickaxe",
		"com.shatteredpixel.shatteredpixeldungeon.items.quest.VaultBeacon",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.BowFragment",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.BrokenHilt",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.BrokenStaff",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.CloakScrap",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.SealShard",
		"com.shatteredpixel.shatteredpixeldungeon.items.remains.TornPage",
	};

	private static final String[] C15 = {   // СУМКИ
		"com.shatteredpixel.shatteredpixeldungeon.items.bags.MagicalHolster",
		"com.shatteredpixel.shatteredpixeldungeon.items.bags.PotionBandolier",
		"com.shatteredpixel.shatteredpixeldungeon.items.bags.ScrollHolder",
		"com.shatteredpixel.shatteredpixeldungeon.items.bags.VelvetPouch",
	};

	private static final String[] C16 = {   // ПРОЧЕЕ
		"com.shatteredpixel.shatteredpixeldungeon.items.Amulet",
		"com.shatteredpixel.shatteredpixeldungeon.items.Ankh",
		"com.shatteredpixel.shatteredpixeldungeon.items.ArcaneResin",
		"com.shatteredpixel.shatteredpixeldungeon.items.BrokenSeal",
		"com.shatteredpixel.shatteredpixeldungeon.items.Dewdrop",
		"com.shatteredpixel.shatteredpixeldungeon.items.EnergyCrystal",
		"com.shatteredpixel.shatteredpixeldungeon.items.Gold",
		"com.shatteredpixel.shatteredpixeldungeon.items.Honeypot",
		"com.shatteredpixel.shatteredpixeldungeon.items.Honeypot$ShatteredPot",
		"com.shatteredpixel.shatteredpixeldungeon.items.KingsCrown",
		"com.shatteredpixel.shatteredpixeldungeon.items.LiquidMetal",
		"com.shatteredpixel.shatteredpixeldungeon.items.LostBackpack",
		"com.shatteredpixel.shatteredpixeldungeon.items.Stylus",
		"com.shatteredpixel.shatteredpixeldungeon.items.TengusMask",
		"com.shatteredpixel.shatteredpixeldungeon.items.Torch",
		"com.shatteredpixel.shatteredpixeldungeon.items.Waterskin",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.SpiritBow",
		"com.shatteredpixel.shatteredpixeldungeon.items.weapon.curses.Explosive$ExplosiveCurseBomb",
	};

	private static final String[][] ALL = {
		C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, C13, C14, C15, C16
	};

	private AdminCatalog() {
	}

	static String[] items( int category ) {
		return ALL[category];
	}
}
